version: '3.1'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - 5678:5678
    environment:
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourpassword
      - N8N_WEBHOOK_URL=https://your-final-url.com/
    volumes:
      - ./n8n-data:/home/node/.n8n
